name: Create dev branch CI/CD pipeline with Github actions
on:
  create:

  delete:

jobs:
  run_on_branch_created:
    runs-on: ubuntu-latest
    steps:
      - name: run log message
        run: echo ${{ github }}